### ISSUE TITLE
Does this extension store content accross instances of chrome?

### ISSUE THREAD

**Issue by ted-strauss-K1** [furbos/bookmarks-tagger#13]
I use this extension on my work and home computers.
Are the bookmarks get merged together?

**Comment by furbos** [comment]
Hi. Unfortunately no. However I'm currently experimenting with Google Drive and storing bookmarks there.

**Comment by ted-strauss-K1** [comment]
Ok, good to know.
Google drive seems like a good way to go.
Thanks for the sweet extension.
