### ISSUE TITLE
Saving does not work on Chromium

### ISSUE THREAD

**Issue by matteocam** [furbos/bookmarks-tagger#9]
The extension UI seems to work smoothly, but when you press the Save button nothing happens.
This issue seems not to be present on Chrome instead.

**Comment by furbos** [comment]
Thank you for your report.
May I ask you which version of Chromium you use please?

**Comment by matteocam** [comment]
Chromium 20.0.1132.47 Ubuntu 12.04

**Comment by furbos** [comment]
Fixed in v1.1. Will be pushed to the webstore later today.
